// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvckVUK6sgrkKJo_3d21tAH1CG_VIkM_s',
    appId: '1:514267938509:web:5fa3dfca22edf35a7cf384',
    messagingSenderId: '514267938509',
    projectId: 'klikkantinapp',
    authDomain: 'klikkantinapp.firebaseapp.com',
    storageBucket: 'klikkantinapp.firebasestorage.app',
    measurementId: 'G-5FZ6ZXZQDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMJgOaY12AsqAQ95qNAfAGrYWsZ7waM2A',
    appId: '1:514267938509:android:b436742eb057916e7cf384',
    messagingSenderId: '514267938509',
    projectId: 'klikkantinapp',
    storageBucket: 'klikkantinapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXie2y93EYvNPmyMHpnVUDDqmS2NEU60Y',
    appId: '1:514267938509:ios:09db0fdac69e9cae7cf384',
    messagingSenderId: '514267938509',
    projectId: 'klikkantinapp',
    storageBucket: 'klikkantinapp.firebasestorage.app',
    iosBundleId: 'com.example.theCaterlinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXie2y93EYvNPmyMHpnVUDDqmS2NEU60Y',
    appId: '1:514267938509:ios:09db0fdac69e9cae7cf384',
    messagingSenderId: '514267938509',
    projectId: 'klikkantinapp',
    storageBucket: 'klikkantinapp.firebasestorage.app',
    iosBundleId: 'com.example.theCaterlinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvckVUK6sgrkKJo_3d21tAH1CG_VIkM_s',
    appId: '1:514267938509:web:a85b74fe2fb0f2bd7cf384',
    messagingSenderId: '514267938509',
    projectId: 'klikkantinapp',
    authDomain: 'klikkantinapp.firebaseapp.com',
    storageBucket: 'klikkantinapp.firebasestorage.app',
    measurementId: 'G-6S838E67M5',
  );

}